version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.5
  - dependency-name: Npgsql
    versions:
    - 5.0.4
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.3
    - 5.0.4
