kind: pipeline
type: docker
name: build
steps:

- name: Prepare Tessdata docker image
  image: docker:latest
  depends_on: [ "clone" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build -t moderras/telegramsearchbot:tessdata-nightly-$(date +%F) -f ./Dockerfile.tessdata .
    - docker build -t moderras/telegramsearchbot:tessdata-latest -f ./Dockerfile.tessdata .

- name: Build Telegram Search Bot
  image: docker:latest
  depends_on: [ "clone" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build -t moderras/telegramsearchbot:build -f ./Dockerfile.build .

- name: Build Tesseract
  image: docker:latest
  depends_on: [ "clone" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build -t moderras/telegramsearchbot:tesseract-nightly-$(date +%F) -f ./Dockerfile.tesseract .
    - docker build -t moderras/telegramsearchbot:tesseract-latest -f ./Dockerfile.tesseract .


- name: Build docker image
  image: docker:latest
  depends_on: [ "Prepare Tessdata docker image", "Build Telegram Search Bot", "Build Tesseract" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build -t moderras/telegramsearchbot:nightly-$(date +%F) -f ./Dockerfile .
    - docker build -t moderras/telegramsearchbot:latest -f ./Dockerfile .


- name: Push docker image
  image: docker:latest
  depends_on: [ "Build docker image" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push moderras/telegramsearchbot:nightly-$(date +%F)
    - docker push moderras/telegramsearchbot:latest

- name: Push Tessdata docker image
  image: docker:latest
  depends_on: [ "Prepare Tessdata docker image" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push moderras/telegramsearchbot:tessdata-nightly-$(date +%F)
    - docker push moderras/telegramsearchbot:tessdata-latest

- name: Push Tesseract docker image
  image: docker:latest
  depends_on: [ "Build Tesseract" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push moderras/telegramsearchbot:tesseract-nightly-$(date +%F)
    - docker push moderras/telegramsearchbot:tesseract-latest

- name: Delete local docker image
  image: docker:latest
  depends_on: [ "Push docker image" ]
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker rmi moderras/telegramsearchbot:nightly-$(date +%F)
    - docker rmi moderras/telegramsearchbot:latest

- name: Send Telegram notification
  image: appleboy/drone-telegram
  depends_on: [ "Delete local docker image" ]
  settings:
    token: 
      from_secret: bot_token
    to: 
      from_secret: userid
    message: >
      {{#success build.status}}
         Telegram Search Bot build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

trigger:
  branch:
  - master
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
