kind: pipeline
type: docker
name: build
steps:

- name: build docker image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build -t moderras/telegramsearchbot:nightly-$(date +%F) -f ./Dockerfile .
    - docker build -t moderras/telegramsearchbot:latest -f ./Dockerfile .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push moderras/telegramsearchbot:nightly-$(date +%F)
    - docker push moderras/telegramsearchbot:latest
    - docker rmi moderras/telegramsearchbot:nightly-$(date +%F)
    - docker rmi moderras/telegramsearchbot:latest

trigger:
  branch:
  - master
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
