services:
  - docker

language: generic

script:
  - docker build -t moderras/telegramsearchbot:nightly-$(date +%F) -f ./Dockerfile .
  - docker build -t moderras/telegramsearchbot:latest -f ./Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moderras/telegramsearchbot:nightly-$(date +%F)
  - docker push moderras/telegramsearchbot:latest