# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '1.0.$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build And Push image
  jobs:
  - job: BuildAndPush
    displayName: BuildAndPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'moderras/telegramsearchbot'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag),latest'
    - task: Docker@2
      displayName: Logout to Docker Hub
      inputs:
        containerRegistry: 'DockerHub'
        command: 'logout'
