version: '3'
services:
  tgsb:
    image: moderras/telegramsearchbot
    env_file: .env
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    depends_on:
      - redis
      - pgsql
      - sonic
      - telegram-bot-api
    restart: always
  redis:
    image: redis
    restart: always
  pgsql:
    image: postgres
    env_file: .env
    volumes:
      - ./data:/var/lib/pgsql
    restart: always
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    volumes:
      - ./sonic:/var/lib/sonic/store/
      - ./sonic.cfg:/etc/sonic.cfg
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "TELEGRAM_API_ID"
      TELEGRAM_API_HASH: "TELEGRAM_API_HASH"
      TELEGRAM_STAT: 1
      TELEGRAM_LOCAL: 1
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api