version: '3'
services:
  tgsb:
    image: moderras/telegramsearchbot
    env_file: .env
    volumes:
      - ./tmp:/tmp
      - ./db:/data/TelegramSearchBot
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    depends_on:
      - telegram-bot-api
    restart: always

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "TELEGRAM_API_ID"
      TELEGRAM_API_HASH: "TELEGRAM_API_HASH"
      TELEGRAM_STAT: 1
      TELEGRAM_LOCAL: 1
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api