FROM moderras/dotnetsdk:5.0 AS build-env
WORKDIR /app

# Copy everything else and build
COPY . ./
RUN dotnet publish ./TelegramSearchBot/TelegramSearchBot.csproj -c Release -o out -r linux-x64 --self-contained false && \
