FROM moderras/dotnetsdk:5.0 AS build-env
WORKDIR /app

RUN apt update -y && \
    apt install wget zip -y && \
    mkdir -p /app/out/tessdata && \
    cd /app/out/tessdata && \
    wget https://github.com/tesseract-ocr/tessdata/raw/main/chi_sim.traineddata
