// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramSearchBot.Model;

#nullable disable

namespace TelegramSearchBot.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20250601101450_AddModelCapabilities")]
    partial class AddModelCapabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TelegramSearchBot.Model.Data.AppConfigurationItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppConfigurationItems");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ChannelWithModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LLMChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LLMChannelId");

                    b.ToTable("ChannelsWithModel");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ConversationSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullContent")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVectorized")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "StartTime", "EndTime");

                    b.ToTable("ConversationSegments");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ConversationSegmentMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConversationSegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationSegmentId");

                    b.HasIndex("MessageDataId");

                    b.ToTable("ConversationSegmentMessages");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.GroupData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlacklist")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsForum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupData");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.GroupSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManagerGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LLMModelName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("GroupSettings");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.LLMChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gateway")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Parallel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LLMChannels");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.MemoryGraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEntity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemoryGraphs");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FromUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplyToMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplyToUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.MessageExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageDataId");

                    b.ToTable("MessageExtensions");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ModelCapability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelWithModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelWithModelId");

                    b.ToTable("ModelCapabilities");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.SearchPageCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchOptionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchPageCaches");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ShortUrlMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpandedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalUrl");

                    b.ToTable("ShortUrlMappings");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.TelegramFileCacheEntry", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CacheKey");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.ToTable("TelegramFileCacheEntries");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.UserData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.UserWithGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UsersWithGroup");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ChannelWithModel", b =>
                {
                    b.HasOne("TelegramSearchBot.Model.Data.LLMChannel", "LLMChannel")
                        .WithMany("Models")
                        .HasForeignKey("LLMChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LLMChannel");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ConversationSegmentMessage", b =>
                {
                    b.HasOne("TelegramSearchBot.Model.Data.ConversationSegment", "ConversationSegment")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramSearchBot.Model.Data.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationSegment");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.MessageExtension", b =>
                {
                    b.HasOne("TelegramSearchBot.Model.Data.Message", "Message")
                        .WithMany("MessageExtensions")
                        .HasForeignKey("MessageDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ModelCapability", b =>
                {
                    b.HasOne("TelegramSearchBot.Model.Data.ChannelWithModel", "ChannelWithModel")
                        .WithMany("Capabilities")
                        .HasForeignKey("ChannelWithModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelWithModel");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ChannelWithModel", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.ConversationSegment", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.LLMChannel", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("TelegramSearchBot.Model.Data.Message", b =>
                {
                    b.Navigation("MessageExtensions");
                });
#pragma warning restore 612, 618
        }
    }
}
