# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Push To Docker 

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish
      run: dotnet publish ./TelegramSearchBot/TelegramSearchBot.csproj -c Release -o /app/ --self-contained false
    - name: Online Test
      env:
        EnableAutoOCR: true
        IsLocalAPI: false
        BotToken: ${{ secrets.BOTTOKEN }}
        AdminId: ${{ secrets.ADMINID }}
      run: dotnet /app/TelegramSearchBot.dll & sleep 1800; kill $!;